name: Run linters and formatters

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install nox
      run: pip install nox
    - name: Install dependencies
      run: pip install -r requirements-dev.txt
    - name: Run cop session
      run: nox --sessions cop
